from string import ascii_lowercase


ASSET_MAX_FOR_TYPE_IN_POINT = 5
ASSET_REPRODUCTION_PROBABILITY = 0.5
DNA_BASES = ascii_lowercase
DNA_SIZE = 26
INDIVIDUAL_HAPPINESS_UNIT = 1
INDIVIDUAL_MAX_AGE = 100
INDIVIDUAL_ASSASSINATION_PROBABILITY = 0.01
INDIVIDUAL_DAILY_STARVATION_PROBABILITY = 0.05
INDIVIDUAL_DEATH_PROBABILITY = 0.01
INDIVIDUAL_REPRODUCTION_PROBABILITY = 0.5
PREFERENCE_MAX_VALUE = 0.9
PREFERENCE_MIN_VALUE = 0.1
PREFERENCE_RANDOMNESS_DELTA = 0.05
