from string import ascii_lowercase


DNA_BASES = ascii_lowercase
DNA_SIZE = 26
INDIVIDUAL_HAPPINESS_UNIT = 10
INDIVIDUAL_MAX_AGE = 100
PREFERENCE_MAX_VALUE = 0.9
PREFERENCE_MIN_VALUE = 0.1
PREFERENCE_RANDOMNESS_DELTA = 0.05
